version: "2.0"

services:
  registration:
    build: 
      context: .
    ports:
      - 3000

  web:
    build:
      context: .
      dockerfile: DockerNginx
    links:
      - registration:registration
    ports:
      - "444:443"
